--Total revenue generated by hotels

SELECT hotel,
       SUM(adr * (stays_in_week_nights + stays_in_weekend_nights)) AS total_revenue
FROM hotel_cleaned
WHERE is_canceled = 0
GROUP BY hotel;

-- Revenue generated by month

SELECT arrival_date_month as months,
    SUM(adr * (stays_in_week_nights + stays_in_weekend_nights)) AS total_revenue
FROM hotel_cleaned
WHERE is_canceled = 0
group by arrival_date_month 
order by total_revenue desc
--Cancellation Rate %


;WITH total_book AS (
    SELECT 
        COUNT(*) AS total_booking,
        SUM(CASE WHEN is_canceled = 1 THEN 1 ELSE 0 END) AS total_cancelled
    FROM hotel_cleaned
)

SELECT 
    total_booking,
    total_cancelled,
    (total_cancelled * 1.0 / total_booking) AS cancellation_rate
FROM total_book 
;
--Revenue by Market Segment
SELECT market_segment,
    SUM(adr * (stays_in_week_nights + stays_in_weekend_nights)) AS total_revenue
FROM hotel_cleaned
WHERE is_canceled = 0
group by market_segment
order by market_segment desc

-- Average stay duration
SELECT 
    hotel,
    AVG(stays_in_week_nights + stays_in_weekend_nights) AS avg_stay
FROM hotel_cleaned
GROUP BY hotel

-- Average Daily Rate by hotel
SELECT 
    hotel,
    AVG(adr) AS avg_price
FROM hotel_cleaned
WHERE is_canceled = 0
GROUP BY hotel;
-- Cancellation by market segment
SELECT 
    market_segment,
    COUNT(*) AS total,
    SUM(CASE WHEN is_canceled = 1 THEN 1 ELSE 0 END) AS cancelled,
    (SUM(CASE WHEN is_canceled = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS cancel_rate
FROM hotel_cleaned
GROUP BY market_segment
ORDER BY cancel_rate DESC;

-- Lead time vs cancellation
SELECT 
    CASE 
        WHEN lead_time < 30 THEN 'Last Minute'
        WHEN lead_time BETWEEN 30 AND 90 THEN 'Medium'
        ELSE 'Early Booking'
    END AS booking_type,
    COUNT(*) AS total_bookings,
    SUM(CASE WHEN is_canceled = 1 THEN 1 ELSE 0 END) AS cancelled,
    (SUM(CASE WHEN is_canceled = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS cancel_rate
FROM hotel_cleaned
GROUP BY 
    CASE 
        WHEN lead_time < 30 THEN 'Last Minute'
        WHEN lead_time BETWEEN 30 AND 90 THEN 'Medium'
        ELSE 'Early Booking'
    END;
-- total booking by market segment 


SELECT 
    hotel,
    market_segment,
    COUNT(*) AS total_bookings,
    SUM(CASE WHEN is_canceled = 1 THEN 1 ELSE 0 END) AS cancelled,
    (SUM(CASE WHEN is_canceled = 1 THEN 1 ELSE 0 END) * 1.0 / COUNT(*)) AS cancel_rate
FROM hotel_cleaned
GROUP BY hotel, market_segment;